### ISSUE TITLE
AOP

### ISSUE THREAD

**Issue by FGRibreau** [bnoguchi/hooks-js#4]
Nice project !

Maybe you do not know, but what you're doing seems to be like Aspect Oriented Programming (AOP). Therefore you may be interested by similar projects like [surround](https://github.com/vesln/surround) or [Javascript-Hooker](javascript-hooker) :)

**Comment by bnoguchi** [comment]
Thanks. I'm familiar with AOP. Thanks for the heads up on the projects; I'll take a look when I have time.
